# Analyzing Chess Tournament Results

This notebook is about the 3rd Project of DAV 5400 course. We will create a csv file from a text file which contains players' information in a chess tournament. Using that file, we will extract the information of players' full name, state, total number of points, pre-tournament rating and opponents' average pre-tournament ratings. Our solution is based on extensive use of for loops, regex methods, list and string methods. We will first import the relevant Python libraries, then upload the text file into the notebook, and extract the relevant data using aforementioned methods.

In [1]:
# Importing the libraries 

import pandas as pd
import numpy as np
import re
import csv

In [2]:
# upload the text file from computer
# store each line in a list

file = []
with open("tournamentinfo.txt") as csvfile: 
    
# Using readCVS reading csvfile  

    readCSV = csv.reader(csvfile)
    for i in readCSV:
        file.append(i)

file

[['-----------------------------------------------------------------------------------------'],
 [' Pair | Player Name                     |Total|Round|Round|Round|Round|Round|Round|Round| '],
 [' Num  | USCF ID / Rtg (Pre->Post)       | Pts |  1  |  2  |  3  |  4  |  5  |  6  |  7  | '],
 ['-----------------------------------------------------------------------------------------'],
 ['    1 | GARY HUA                        |6.0  |W  39|W  21|W  18|W  14|W   7|D  12|D   4|'],
 ['   ON | 15445895 / R: 1794   ->1817     |N:2  |W    |B    |W    |B    |W    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['    2 | DAKSHESH DARURI                 |6.0  |W  63|W  58|L   4|W  17|W  16|W  20|W   7|'],
 ['   MI | 14598900 / R: 1553   ->1663     |N:2  |B    |W    |B    |W    |B    |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['    3 | ADITYA BAJAJ                    |6.0  |L   8|W  61|W  25|W  21|W  11|W  13|W  12|'],
 ['   MI | 14959604 / R: 1384   ->1640     |N:2  |W    |B    |W    |B    |W    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['    4 | PATRICK H SCHILLING             |5.5  |W  23|D  28|W   2|W  26|D   5|W  19|D   1|'],
 ['   MI | 12616049 / R: 1716   ->1744     |N:2  |W    |B    |W    |B    |W    |B    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['    5 | HANSHI ZUO                      |5.5  |W  45|W  37|D  12|D  13|D   4|W  14|W  17|'],
 ['   MI | 14601533 / R: 1655   ->1690     |N:2  |B    |W    |B    |W    |B    |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['    6 | HANSEN SONG                     |5.0  |W  34|D  29|L  11|W  35|D  10|W  27|W  21|'],
 ['   OH | 15055204 / R: 1686   ->1687     |N:3  |W    |B    |W    |B    |B    |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['    7 | GARY DEE SWATHELL               |5.0  |W  57|W  46|W  13|W  11|L   1|W   9|L   2|'],
 ['   MI | 11146376 / R: 1649   ->1673     |N:3  |W    |B    |W    |B    |B    |W    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['    8 | EZEKIEL HOUGHTON                |5.0  |W   3|W  32|L  14|L   9|W  47|W  28|W  19|'],
 ['   MI | 15142253 / R: 1641P17->1657P24  |N:3  |B    |W    |B    |W    |B    |W    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['    9 | STEFANO LEE                     |5.0  |W  25|L  18|W  59|W   8|W  26|L   7|W  20|'],
 ['   ON | 14954524 / R: 1411   ->1564     |N:2  |W    |B    |W    |B    |W    |B    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   10 | ANVIT RAO                       |5.0  |D  16|L  19|W  55|W  31|D   6|W  25|W  18|'],
 ['   MI | 14150362 / R: 1365   ->1544     |N:3  |W    |W    |B    |B    |W    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   11 | CAMERON WILLIAM MC LEMAN        |4.5  |D  38|W  56|W   6|L   7|L   3|W  34|W  26|'],
 ['   MI | 12581589 / R: 1712   ->1696     |N:3  |B    |W    |B    |W    |B    |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   12 | KENNETH J TACK                  |4.5  |W  42|W  33|D   5|W  38|H    |D   1|L   3|'],
 ['   MI | 12681257 / R: 1663   ->1670     |N:3  |W    |B    |W    |B    |     |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   13 | TORRANCE HENRY JR               |4.5  |W  36|W  27|L   7|D   5|W  33|L   3|W  32|'],
 ['   MI | 15082995 / R: 1666   ->1662     |N:3  |B    |W    |B    |B    |W    |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   14 | BRADLEY SHAW                    |4.5  |W  54|W  44|W   8|L   1|D  27|L   5|W  31|'],
 ['   MI | 10131499 / R: 1610   ->1618     |N:3  |W    |B    |W    |W    |B    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   15 | ZACHARY JAMES HOUGHTON          |4.5  |D  19|L  16|W  30|L  22|W  54|W  33|W  38|'],
 ['   MI | 15619130 / R: 1220P13->1416P20  |N:3  |B    |B    |W    |W    |B    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   16 | MIKE NIKITIN                    |4.0  |D  10|W  15|H    |W  39|L   2|W  36|U    |'],
 ['   MI | 10295068 / R: 1604   ->1613     |N:3  |B    |W    |     |B    |W    |B    |     |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   17 | RONALD GRZEGORCZYK              |4.0  |W  48|W  41|L  26|L   2|W  23|W  22|L   5|'],
 ['   MI | 10297702 / R: 1629   ->1610     |N:3  |W    |B    |W    |B    |W    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   18 | DAVID SUNDEEN                   |4.0  |W  47|W   9|L   1|W  32|L  19|W  38|L  10|'],
 ['   MI | 11342094 / R: 1600   ->1600     |N:3  |B    |W    |B    |W    |B    |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   19 | DIPANKAR ROY                    |4.0  |D  15|W  10|W  52|D  28|W  18|L   4|L   8|'],
 ['   MI | 14862333 / R: 1564   ->1570     |N:3  |W    |B    |W    |B    |W    |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   20 | JASON ZHENG                     |4.0  |L  40|W  49|W  23|W  41|W  28|L   2|L   9|'],
 ['   MI | 14529060 / R: 1595   ->1569     |N:4  |W    |B    |W    |B    |W    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   21 | DINH DANG BUI                   |4.0  |W  43|L   1|W  47|L   3|W  40|W  39|L   6|'],
 ['   ON | 15495066 / R: 1563P22->1562     |N:3  |B    |W    |B    |W    |W    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   22 | EUGENE L MCCLURE                |4.0  |W  64|D  52|L  28|W  15|H    |L  17|W  40|'],
 ['   MI | 12405534 / R: 1555   ->1529     |N:4  |W    |B    |W    |B    |     |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   23 | ALAN BUI                        |4.0  |L   4|W  43|L  20|W  58|L  17|W  37|W  46|'],
 ['   ON | 15030142 / R: 1363   ->1371     |     |B    |W    |B    |W    |B    |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   24 | MICHAEL R ALDRICH               |4.0  |L  28|L  47|W  43|L  25|W  60|W  44|W  39|'],
 ['   MI | 13469010 / R: 1229   ->1300     |N:4  |B    |W    |B    |B    |W    |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   25 | LOREN SCHWIEBERT                |3.5  |L   9|W  53|L   3|W  24|D  34|L  10|W  47|'],
 ['   MI | 12486656 / R: 1745   ->1681     |N:4  |B    |W    |B    |W    |B    |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   26 | MAX ZHU                         |3.5  |W  49|W  40|W  17|L   4|L   9|D  32|L  11|'],
 ['   ON | 15131520 / R: 1579   ->1564     |N:4  |B    |W    |B    |W    |B    |W    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   27 | GAURAV GIDWANI                  |3.5  |W  51|L  13|W  46|W  37|D  14|L   6|U    |'],
 ['   MI | 14476567 / R: 1552   ->1539     |N:4  |W    |B    |W    |B    |W    |B    |     |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   28 | SOFIA ADINA STANESCU-BELLU      |3.5  |W  24|D   4|W  22|D  19|L  20|L   8|D  36|'],
 ['   MI | 14882954 / R: 1507   ->1513     |N:3  |W    |W    |B    |W    |B    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   29 | CHIEDOZIE OKORIE                |3.5  |W  50|D   6|L  38|L  34|W  52|W  48|U    |'],
 ['   MI | 15323285 / R: 1602P6 ->1508P12  |N:4  |B    |W    |B    |W    |W    |B    |     |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   30 | GEORGE AVERY JONES              |3.5  |L  52|D  64|L  15|W  55|L  31|W  61|W  50|'],
 ['   ON | 12577178 / R: 1522   ->1444     |     |W    |B    |B    |W    |W    |B    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   31 | RISHI SHETTY                    |3.5  |L  58|D  55|W  64|L  10|W  30|W  50|L  14|'],
 ['   MI | 15131618 / R: 1494   ->1444     |     |B    |W    |B    |W    |B    |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   32 | JOSHUA PHILIP MATHEWS           |3.5  |W  61|L   8|W  44|L  18|W  51|D  26|L  13|'],
 ['   ON | 14073750 / R: 1441   ->1433     |N:4  |W    |B    |W    |B    |W    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   33 | JADE GE                         |3.5  |W  60|L  12|W  50|D  36|L  13|L  15|W  51|'],
 ['   MI | 14691842 / R: 1449   ->1421     |     |B    |W    |B    |W    |B    |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   34 | MICHAEL JEFFERY THOMAS          |3.5  |L   6|W  60|L  37|W  29|D  25|L  11|W  52|'],
 ['   MI | 15051807 / R: 1399   ->1400     |     |B    |W    |B    |B    |W    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   35 | JOSHUA DAVID LEE                |3.5  |L  46|L  38|W  56|L   6|W  57|D  52|W  48|'],
 ['   MI | 14601397 / R: 1438   ->1392     |     |W    |W    |B    |W    |B    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   36 | SIDDHARTH JHA                   |3.5  |L  13|W  57|W  51|D  33|H    |L  16|D  28|'],
 ['   MI | 14773163 / R: 1355   ->1367     |N:4  |W    |B    |W    |B    |     |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   37 | AMIYATOSH PWNANANDAM            |3.5  |B    |L   5|W  34|L  27|H    |L  23|W  61|'],
 ['   MI | 15489571 / R:  980P12->1077P17  |     |     |B    |W    |W    |     |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   38 | BRIAN LIU                       |3.0  |D  11|W  35|W  29|L  12|H    |L  18|L  15|'],
 ['   MI | 15108523 / R: 1423   ->1439     |N:4  |W    |B    |W    |W    |     |B    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   39 | JOEL R HENDON                   |3.0  |L   1|W  54|W  40|L  16|W  44|L  21|L  24|'],
 ['   MI | 12923035 / R: 1436P23->1413     |N:4  |B    |W    |B    |W    |B    |W    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   40 | FOREST ZHANG                    |3.0  |W  20|L  26|L  39|W  59|L  21|W  56|L  22|'],
 ['   MI | 14892710 / R: 1348   ->1346     |     |B    |B    |W    |W    |B    |W    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   41 | KYLE WILLIAM MURPHY             |3.0  |W  59|L  17|W  58|L  20|X    |U    |U    |'],
 ['   MI | 15761443 / R: 1403P5 ->1341P9   |     |B    |W    |B    |W    |     |     |     |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   42 | JARED GE                        |3.0  |L  12|L  50|L  57|D  60|D  61|W  64|W  56|'],
 ['   MI | 14462326 / R: 1332   ->1256     |     |B    |W    |B    |B    |W    |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   43 | ROBERT GLEN VASEY               |3.0  |L  21|L  23|L  24|W  63|W  59|L  46|W  55|'],
 ['   MI | 14101068 / R: 1283   ->1244     |     |W    |B    |W    |W    |B    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   44 | JUSTIN D SCHILLING              |3.0  |B    |L  14|L  32|W  53|L  39|L  24|W  59|'],
 ['   MI | 15323504 / R: 1199   ->1199     |     |     |W    |B    |B    |W    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   45 | DEREK YAN                       |3.0  |L   5|L  51|D  60|L  56|W  63|D  55|W  58|'],
 ['   MI | 15372807 / R: 1242   ->1191     |     |W    |B    |W    |B    |W    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   46 | JACOB ALEXANDER LAVALLEY        |3.0  |W  35|L   7|L  27|L  50|W  64|W  43|L  23|'],
 ['   MI | 15490981 / R:  377P3 ->1076P10  |     |B    |W    |B    |W    |B    |W    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   47 | ERIC WRIGHT                     |2.5  |L  18|W  24|L  21|W  61|L   8|D  51|L  25|'],
 ['   MI | 12533115 / R: 1362   ->1341     |     |W    |B    |W    |B    |W    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   48 | DANIEL KHAIN                    |2.5  |L  17|W  63|H    |D  52|H    |L  29|L  35|'],
 ['   MI | 14369165 / R: 1382   ->1335     |     |B    |W    |     |B    |     |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   49 | MICHAEL J MARTIN                |2.5  |L  26|L  20|D  63|D  64|W  58|H    |U    |'],
 ['   MI | 12531685 / R: 1291P12->1259P17  |     |W    |W    |B    |W    |B    |     |     |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   50 | SHIVAM JHA                      |2.5  |L  29|W  42|L  33|W  46|H    |L  31|L  30|'],
 ['   MI | 14773178 / R: 1056   ->1111     |     |W    |B    |W    |B    |     |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   51 | TEJAS AYYAGARI                  |2.5  |L  27|W  45|L  36|W  57|L  32|D  47|L  33|'],
 ['   MI | 15205474 / R: 1011   ->1097     |     |B    |W    |B    |W    |B    |W    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   52 | ETHAN GUO                       |2.5  |W  30|D  22|L  19|D  48|L  29|D  35|L  34|'],
 ['   MI | 14918803 / R:  935   ->1092     |N:4  |B    |W    |B    |W    |B    |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   53 | JOSE C YBARRA                   |2.0  |H    |L  25|H    |L  44|U    |W  57|U    |'],
 ['   MI | 12578849 / R: 1393   ->1359     |     |     |B    |     |W    |     |W    |     |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   54 | LARRY HODGE                     |2.0  |L  14|L  39|L  61|B    |L  15|L  59|W  64|'],
 ['   MI | 12836773 / R: 1270   ->1200     |     |B    |B    |W    |     |W    |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   55 | ALEX KONG                       |2.0  |L  62|D  31|L  10|L  30|B    |D  45|L  43|'],
 ['   MI | 15412571 / R: 1186   ->1163     |     |W    |B    |W    |B    |     |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   56 | MARISA RICCI                    |2.0  |H    |L  11|L  35|W  45|H    |L  40|L  42|'],
 ['   MI | 14679887 / R: 1153   ->1140     |     |     |B    |W    |W    |     |B    |W    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   57 | MICHAEL LU                      |2.0  |L   7|L  36|W  42|L  51|L  35|L  53|B    |'],
 ['   MI | 15113330 / R: 1092   ->1079     |     |B    |W    |W    |B    |W    |B    |     |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   58 | VIRAJ MOHILE                    |2.0  |W  31|L   2|L  41|L  23|L  49|B    |L  45|'],
 ['   MI | 14700365 / R:  917   -> 941     |     |W    |B    |W    |B    |W    |     |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   59 | SEAN M MC CORMICK               |2.0  |L  41|B    |L   9|L  40|L  43|W  54|L  44|'],
 ['   MI | 12841036 / R:  853   -> 878     |     |W    |     |B    |B    |W    |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   60 | JULIA SHEN                      |1.5  |L  33|L  34|D  45|D  42|L  24|H    |U    |'],
 ['   MI | 14579262 / R:  967   -> 984     |     |W    |B    |B    |W    |B    |     |     |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   61 | JEZZEL FARKAS                   |1.5  |L  32|L   3|W  54|L  47|D  42|L  30|L  37|'],
 ['   ON | 15771592 / R:  955P11-> 979P18  |     |B    |W    |B    |W    |B    |W    |B    |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   62 | ASHWIN BALAJI                   |1.0  |W  55|U    |U    |U    |U    |U    |U    |'],
 ['   MI | 15219542 / R: 1530   ->1535     |     |B    |     |     |     |     |     |     |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   63 | THOMAS JOSEPH HOSMER            |1.0  |L   2|L  48|D  49|L  43|L  45|H    |U    |'],
 ['   MI | 15057092 / R: 1175   ->1125     |     |W    |B    |W    |B    |B    |     |     |'],
 ['-----------------------------------------------------------------------------------------'],
 ['   64 | BEN LI                          |1.0  |L  22|D  30|L  31|D  49|L  46|L  42|L  54|'],
 ['   MI | 15006561 / R: 1163   ->1112     |     |B    |W    |W    |B    |W    |B    |B    |'],
 ['-----------------------------------------------------------------------------------------']]

## Task 1: To extract the player name and total points into a pandas DataFrame, then convert the text file to the .CSV file.

#### Step 1: To extract player names from the original text file

In [3]:
# get rid of the nested list using list comprehension

chess_1 = [i for line in file for i in line]
chess_1

['-----------------------------------------------------------------------------------------',
 ' Pair | Player Name                     |Total|Round|Round|Round|Round|Round|Round|Round| ',
 ' Num  | USCF ID / Rtg (Pre->Post)       | Pts |  1  |  2  |  3  |  4  |  5  |  6  |  7  | ',
 '-----------------------------------------------------------------------------------------',
 '    1 | GARY HUA                        |6.0  |W  39|W  21|W  18|W  14|W   7|D  12|D   4|',
 '   ON | 15445895 / R: 1794   ->1817     |N:2  |W    |B    |W    |B    |W    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '    2 | DAKSHESH DARURI                 |6.0  |W  63|W  58|L   4|W  17|W  16|W  20|W   7|',
 '   MI | 14598900 / R: 1553   ->1663     |N:2  |B    |W    |B    |W    |B    |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '    3 | ADITYA BAJAJ                    |6.0  |L   8|W  61|W  25|W  21|W  11|W  13|W  12|',
 '   MI | 14959604 / R: 1384   ->1640     |N:2  |W    |B    |W    |B    |W    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '    4 | PATRICK H SCHILLING             |5.5  |W  23|D  28|W   2|W  26|D   5|W  19|D   1|',
 '   MI | 12616049 / R: 1716   ->1744     |N:2  |W    |B    |W    |B    |W    |B    |B    |',
 '-----------------------------------------------------------------------------------------',
 '    5 | HANSHI ZUO                      |5.5  |W  45|W  37|D  12|D  13|D   4|W  14|W  17|',
 '   MI | 14601533 / R: 1655   ->1690     |N:2  |B    |W    |B    |W    |B    |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '    6 | HANSEN SONG                     |5.0  |W  34|D  29|L  11|W  35|D  10|W  27|W  21|',
 '   OH | 15055204 / R: 1686   ->1687     |N:3  |W    |B    |W    |B    |B    |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '    7 | GARY DEE SWATHELL               |5.0  |W  57|W  46|W  13|W  11|L   1|W   9|L   2|',
 '   MI | 11146376 / R: 1649   ->1673     |N:3  |W    |B    |W    |B    |B    |W    |W    |',
 '-----------------------------------------------------------------------------------------',
 '    8 | EZEKIEL HOUGHTON                |5.0  |W   3|W  32|L  14|L   9|W  47|W  28|W  19|',
 '   MI | 15142253 / R: 1641P17->1657P24  |N:3  |B    |W    |B    |W    |B    |W    |W    |',
 '-----------------------------------------------------------------------------------------',
 '    9 | STEFANO LEE                     |5.0  |W  25|L  18|W  59|W   8|W  26|L   7|W  20|',
 '   ON | 14954524 / R: 1411   ->1564     |N:2  |W    |B    |W    |B    |W    |B    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   10 | ANVIT RAO                       |5.0  |D  16|L  19|W  55|W  31|D   6|W  25|W  18|',
 '   MI | 14150362 / R: 1365   ->1544     |N:3  |W    |W    |B    |B    |W    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   11 | CAMERON WILLIAM MC LEMAN        |4.5  |D  38|W  56|W   6|L   7|L   3|W  34|W  26|',
 '   MI | 12581589 / R: 1712   ->1696     |N:3  |B    |W    |B    |W    |B    |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   12 | KENNETH J TACK                  |4.5  |W  42|W  33|D   5|W  38|H    |D   1|L   3|',
 '   MI | 12681257 / R: 1663   ->1670     |N:3  |W    |B    |W    |B    |     |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   13 | TORRANCE HENRY JR               |4.5  |W  36|W  27|L   7|D   5|W  33|L   3|W  32|',
 '   MI | 15082995 / R: 1666   ->1662     |N:3  |B    |W    |B    |B    |W    |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   14 | BRADLEY SHAW                    |4.5  |W  54|W  44|W   8|L   1|D  27|L   5|W  31|',
 '   MI | 10131499 / R: 1610   ->1618     |N:3  |W    |B    |W    |W    |B    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   15 | ZACHARY JAMES HOUGHTON          |4.5  |D  19|L  16|W  30|L  22|W  54|W  33|W  38|',
 '   MI | 15619130 / R: 1220P13->1416P20  |N:3  |B    |B    |W    |W    |B    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   16 | MIKE NIKITIN                    |4.0  |D  10|W  15|H    |W  39|L   2|W  36|U    |',
 '   MI | 10295068 / R: 1604   ->1613     |N:3  |B    |W    |     |B    |W    |B    |     |',
 '-----------------------------------------------------------------------------------------',
 '   17 | RONALD GRZEGORCZYK              |4.0  |W  48|W  41|L  26|L   2|W  23|W  22|L   5|',
 '   MI | 10297702 / R: 1629   ->1610     |N:3  |W    |B    |W    |B    |W    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   18 | DAVID SUNDEEN                   |4.0  |W  47|W   9|L   1|W  32|L  19|W  38|L  10|',
 '   MI | 11342094 / R: 1600   ->1600     |N:3  |B    |W    |B    |W    |B    |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   19 | DIPANKAR ROY                    |4.0  |D  15|W  10|W  52|D  28|W  18|L   4|L   8|',
 '   MI | 14862333 / R: 1564   ->1570     |N:3  |W    |B    |W    |B    |W    |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   20 | JASON ZHENG                     |4.0  |L  40|W  49|W  23|W  41|W  28|L   2|L   9|',
 '   MI | 14529060 / R: 1595   ->1569     |N:4  |W    |B    |W    |B    |W    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   21 | DINH DANG BUI                   |4.0  |W  43|L   1|W  47|L   3|W  40|W  39|L   6|',
 '   ON | 15495066 / R: 1563P22->1562     |N:3  |B    |W    |B    |W    |W    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   22 | EUGENE L MCCLURE                |4.0  |W  64|D  52|L  28|W  15|H    |L  17|W  40|',
 '   MI | 12405534 / R: 1555   ->1529     |N:4  |W    |B    |W    |B    |     |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   23 | ALAN BUI                        |4.0  |L   4|W  43|L  20|W  58|L  17|W  37|W  46|',
 '   ON | 15030142 / R: 1363   ->1371     |     |B    |W    |B    |W    |B    |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   24 | MICHAEL R ALDRICH               |4.0  |L  28|L  47|W  43|L  25|W  60|W  44|W  39|',
 '   MI | 13469010 / R: 1229   ->1300     |N:4  |B    |W    |B    |B    |W    |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   25 | LOREN SCHWIEBERT                |3.5  |L   9|W  53|L   3|W  24|D  34|L  10|W  47|',
 '   MI | 12486656 / R: 1745   ->1681     |N:4  |B    |W    |B    |W    |B    |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   26 | MAX ZHU                         |3.5  |W  49|W  40|W  17|L   4|L   9|D  32|L  11|',
 '   ON | 15131520 / R: 1579   ->1564     |N:4  |B    |W    |B    |W    |B    |W    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   27 | GAURAV GIDWANI                  |3.5  |W  51|L  13|W  46|W  37|D  14|L   6|U    |',
 '   MI | 14476567 / R: 1552   ->1539     |N:4  |W    |B    |W    |B    |W    |B    |     |',
 '-----------------------------------------------------------------------------------------',
 '   28 | SOFIA ADINA STANESCU-BELLU      |3.5  |W  24|D   4|W  22|D  19|L  20|L   8|D  36|',
 '   MI | 14882954 / R: 1507   ->1513     |N:3  |W    |W    |B    |W    |B    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   29 | CHIEDOZIE OKORIE                |3.5  |W  50|D   6|L  38|L  34|W  52|W  48|U    |',
 '   MI | 15323285 / R: 1602P6 ->1508P12  |N:4  |B    |W    |B    |W    |W    |B    |     |',
 '-----------------------------------------------------------------------------------------',
 '   30 | GEORGE AVERY JONES              |3.5  |L  52|D  64|L  15|W  55|L  31|W  61|W  50|',
 '   ON | 12577178 / R: 1522   ->1444     |     |W    |B    |B    |W    |W    |B    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   31 | RISHI SHETTY                    |3.5  |L  58|D  55|W  64|L  10|W  30|W  50|L  14|',
 '   MI | 15131618 / R: 1494   ->1444     |     |B    |W    |B    |W    |B    |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   32 | JOSHUA PHILIP MATHEWS           |3.5  |W  61|L   8|W  44|L  18|W  51|D  26|L  13|',
 '   ON | 14073750 / R: 1441   ->1433     |N:4  |W    |B    |W    |B    |W    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   33 | JADE GE                         |3.5  |W  60|L  12|W  50|D  36|L  13|L  15|W  51|',
 '   MI | 14691842 / R: 1449   ->1421     |     |B    |W    |B    |W    |B    |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   34 | MICHAEL JEFFERY THOMAS          |3.5  |L   6|W  60|L  37|W  29|D  25|L  11|W  52|',
 '   MI | 15051807 / R: 1399   ->1400     |     |B    |W    |B    |B    |W    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   35 | JOSHUA DAVID LEE                |3.5  |L  46|L  38|W  56|L   6|W  57|D  52|W  48|',
 '   MI | 14601397 / R: 1438   ->1392     |     |W    |W    |B    |W    |B    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   36 | SIDDHARTH JHA                   |3.5  |L  13|W  57|W  51|D  33|H    |L  16|D  28|',
 '   MI | 14773163 / R: 1355   ->1367     |N:4  |W    |B    |W    |B    |     |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   37 | AMIYATOSH PWNANANDAM            |3.5  |B    |L   5|W  34|L  27|H    |L  23|W  61|',
 '   MI | 15489571 / R:  980P12->1077P17  |     |     |B    |W    |W    |     |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   38 | BRIAN LIU                       |3.0  |D  11|W  35|W  29|L  12|H    |L  18|L  15|',
 '   MI | 15108523 / R: 1423   ->1439     |N:4  |W    |B    |W    |W    |     |B    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   39 | JOEL R HENDON                   |3.0  |L   1|W  54|W  40|L  16|W  44|L  21|L  24|',
 '   MI | 12923035 / R: 1436P23->1413     |N:4  |B    |W    |B    |W    |B    |W    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   40 | FOREST ZHANG                    |3.0  |W  20|L  26|L  39|W  59|L  21|W  56|L  22|',
 '   MI | 14892710 / R: 1348   ->1346     |     |B    |B    |W    |W    |B    |W    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   41 | KYLE WILLIAM MURPHY             |3.0  |W  59|L  17|W  58|L  20|X    |U    |U    |',
 '   MI | 15761443 / R: 1403P5 ->1341P9   |     |B    |W    |B    |W    |     |     |     |',
 '-----------------------------------------------------------------------------------------',
 '   42 | JARED GE                        |3.0  |L  12|L  50|L  57|D  60|D  61|W  64|W  56|',
 '   MI | 14462326 / R: 1332   ->1256     |     |B    |W    |B    |B    |W    |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   43 | ROBERT GLEN VASEY               |3.0  |L  21|L  23|L  24|W  63|W  59|L  46|W  55|',
 '   MI | 14101068 / R: 1283   ->1244     |     |W    |B    |W    |W    |B    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   44 | JUSTIN D SCHILLING              |3.0  |B    |L  14|L  32|W  53|L  39|L  24|W  59|',
 '   MI | 15323504 / R: 1199   ->1199     |     |     |W    |B    |B    |W    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   45 | DEREK YAN                       |3.0  |L   5|L  51|D  60|L  56|W  63|D  55|W  58|',
 '   MI | 15372807 / R: 1242   ->1191     |     |W    |B    |W    |B    |W    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   46 | JACOB ALEXANDER LAVALLEY        |3.0  |W  35|L   7|L  27|L  50|W  64|W  43|L  23|',
 '   MI | 15490981 / R:  377P3 ->1076P10  |     |B    |W    |B    |W    |B    |W    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   47 | ERIC WRIGHT                     |2.5  |L  18|W  24|L  21|W  61|L   8|D  51|L  25|',
 '   MI | 12533115 / R: 1362   ->1341     |     |W    |B    |W    |B    |W    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   48 | DANIEL KHAIN                    |2.5  |L  17|W  63|H    |D  52|H    |L  29|L  35|',
 '   MI | 14369165 / R: 1382   ->1335     |     |B    |W    |     |B    |     |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   49 | MICHAEL J MARTIN                |2.5  |L  26|L  20|D  63|D  64|W  58|H    |U    |',
 '   MI | 12531685 / R: 1291P12->1259P17  |     |W    |W    |B    |W    |B    |     |     |',
 '-----------------------------------------------------------------------------------------',
 '   50 | SHIVAM JHA                      |2.5  |L  29|W  42|L  33|W  46|H    |L  31|L  30|',
 '   MI | 14773178 / R: 1056   ->1111     |     |W    |B    |W    |B    |     |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   51 | TEJAS AYYAGARI                  |2.5  |L  27|W  45|L  36|W  57|L  32|D  47|L  33|',
 '   MI | 15205474 / R: 1011   ->1097     |     |B    |W    |B    |W    |B    |W    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   52 | ETHAN GUO                       |2.5  |W  30|D  22|L  19|D  48|L  29|D  35|L  34|',
 '   MI | 14918803 / R:  935   ->1092     |N:4  |B    |W    |B    |W    |B    |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   53 | JOSE C YBARRA                   |2.0  |H    |L  25|H    |L  44|U    |W  57|U    |',
 '   MI | 12578849 / R: 1393   ->1359     |     |     |B    |     |W    |     |W    |     |',
 '-----------------------------------------------------------------------------------------',
 '   54 | LARRY HODGE                     |2.0  |L  14|L  39|L  61|B    |L  15|L  59|W  64|',
 '   MI | 12836773 / R: 1270   ->1200     |     |B    |B    |W    |     |W    |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   55 | ALEX KONG                       |2.0  |L  62|D  31|L  10|L  30|B    |D  45|L  43|',
 '   MI | 15412571 / R: 1186   ->1163     |     |W    |B    |W    |B    |     |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   56 | MARISA RICCI                    |2.0  |H    |L  11|L  35|W  45|H    |L  40|L  42|',
 '   MI | 14679887 / R: 1153   ->1140     |     |     |B    |W    |W    |     |B    |W    |',
 '-----------------------------------------------------------------------------------------',
 '   57 | MICHAEL LU                      |2.0  |L   7|L  36|W  42|L  51|L  35|L  53|B    |',
 '   MI | 15113330 / R: 1092   ->1079     |     |B    |W    |W    |B    |W    |B    |     |',
 '-----------------------------------------------------------------------------------------',
 '   58 | VIRAJ MOHILE                    |2.0  |W  31|L   2|L  41|L  23|L  49|B    |L  45|',
 '   MI | 14700365 / R:  917   -> 941     |     |W    |B    |W    |B    |W    |     |B    |',
 '-----------------------------------------------------------------------------------------',
 '   59 | SEAN M MC CORMICK               |2.0  |L  41|B    |L   9|L  40|L  43|W  54|L  44|',
 '   MI | 12841036 / R:  853   -> 878     |     |W    |     |B    |B    |W    |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   60 | JULIA SHEN                      |1.5  |L  33|L  34|D  45|D  42|L  24|H    |U    |',
 '   MI | 14579262 / R:  967   -> 984     |     |W    |B    |B    |W    |B    |     |     |',
 '-----------------------------------------------------------------------------------------',
 '   61 | JEZZEL FARKAS                   |1.5  |L  32|L   3|W  54|L  47|D  42|L  30|L  37|',
 '   ON | 15771592 / R:  955P11-> 979P18  |     |B    |W    |B    |W    |B    |W    |B    |',
 '-----------------------------------------------------------------------------------------',
 '   62 | ASHWIN BALAJI                   |1.0  |W  55|U    |U    |U    |U    |U    |U    |',
 '   MI | 15219542 / R: 1530   ->1535     |     |B    |     |     |     |     |     |     |',
 '-----------------------------------------------------------------------------------------',
 '   63 | THOMAS JOSEPH HOSMER            |1.0  |L   2|L  48|D  49|L  43|L  45|H    |U    |',
 '   MI | 15057092 / R: 1175   ->1125     |     |W    |B    |W    |B    |B    |     |     |',
 '-----------------------------------------------------------------------------------------',
 '   64 | BEN LI                          |1.0  |L  22|D  30|L  31|D  49|L  46|L  42|L  54|',
 '   MI | 15006561 / R: 1163   ->1112     |     |B    |W    |W    |B    |W    |B    |B    |',
 '-----------------------------------------------------------------------------------------']

Since every third line consisting all with hypen, we need the remove that line

In [4]:
# get rid of the third line using list comprehension and conditionals
# if index numbr of line is not exactly divide by 3, store that line in a seperate list

chess_2 = [chess_1[i] for i in range(len(chess_1)) if i%3 != 0]

#check
chess_2

[' Pair | Player Name                     |Total|Round|Round|Round|Round|Round|Round|Round| ',
 ' Num  | USCF ID / Rtg (Pre->Post)       | Pts |  1  |  2  |  3  |  4  |  5  |  6  |  7  | ',
 '    1 | GARY HUA                        |6.0  |W  39|W  21|W  18|W  14|W   7|D  12|D   4|',
 '   ON | 15445895 / R: 1794   ->1817     |N:2  |W    |B    |W    |B    |W    |B    |W    |',
 '    2 | DAKSHESH DARURI                 |6.0  |W  63|W  58|L   4|W  17|W  16|W  20|W   7|',
 '   MI | 14598900 / R: 1553   ->1663     |N:2  |B    |W    |B    |W    |B    |W    |B    |',
 '    3 | ADITYA BAJAJ                    |6.0  |L   8|W  61|W  25|W  21|W  11|W  13|W  12|',
 '   MI | 14959604 / R: 1384   ->1640     |N:2  |W    |B    |W    |B    |W    |B    |W    |',
 '    4 | PATRICK H SCHILLING             |5.5  |W  23|D  28|W   2|W  26|D   5|W  19|D   1|',
 '   MI | 12616049 / R: 1716   ->1744     |N:2  |W    |B    |W    |B    |W    |B    |B    |',
 '    5 | HANSHI ZUO                      |5.5  |W  45|W  37|D  12|D  13|D   4|W  14|W  17|',
 '   MI | 14601533 / R: 1655   ->1690     |N:2  |B    |W    |B    |W    |B    |W    |B    |',
 '    6 | HANSEN SONG                     |5.0  |W  34|D  29|L  11|W  35|D  10|W  27|W  21|',
 '   OH | 15055204 / R: 1686   ->1687     |N:3  |W    |B    |W    |B    |B    |W    |B    |',
 '    7 | GARY DEE SWATHELL               |5.0  |W  57|W  46|W  13|W  11|L   1|W   9|L   2|',
 '   MI | 11146376 / R: 1649   ->1673     |N:3  |W    |B    |W    |B    |B    |W    |W    |',
 '    8 | EZEKIEL HOUGHTON                |5.0  |W   3|W  32|L  14|L   9|W  47|W  28|W  19|',
 '   MI | 15142253 / R: 1641P17->1657P24  |N:3  |B    |W    |B    |W    |B    |W    |W    |',
 '    9 | STEFANO LEE                     |5.0  |W  25|L  18|W  59|W   8|W  26|L   7|W  20|',
 '   ON | 14954524 / R: 1411   ->1564     |N:2  |W    |B    |W    |B    |W    |B    |B    |',
 '   10 | ANVIT RAO                       |5.0  |D  16|L  19|W  55|W  31|D   6|W  25|W  18|',
 '   MI | 14150362 / R: 1365   ->1544     |N:3  |W    |W    |B    |B    |W    |B    |W    |',
 '   11 | CAMERON WILLIAM MC LEMAN        |4.5  |D  38|W  56|W   6|L   7|L   3|W  34|W  26|',
 '   MI | 12581589 / R: 1712   ->1696     |N:3  |B    |W    |B    |W    |B    |W    |B    |',
 '   12 | KENNETH J TACK                  |4.5  |W  42|W  33|D   5|W  38|H    |D   1|L   3|',
 '   MI | 12681257 / R: 1663   ->1670     |N:3  |W    |B    |W    |B    |     |W    |B    |',
 '   13 | TORRANCE HENRY JR               |4.5  |W  36|W  27|L   7|D   5|W  33|L   3|W  32|',
 '   MI | 15082995 / R: 1666   ->1662     |N:3  |B    |W    |B    |B    |W    |W    |B    |',
 '   14 | BRADLEY SHAW                    |4.5  |W  54|W  44|W   8|L   1|D  27|L   5|W  31|',
 '   MI | 10131499 / R: 1610   ->1618     |N:3  |W    |B    |W    |W    |B    |B    |W    |',
 '   15 | ZACHARY JAMES HOUGHTON          |4.5  |D  19|L  16|W  30|L  22|W  54|W  33|W  38|',
 '   MI | 15619130 / R: 1220P13->1416P20  |N:3  |B    |B    |W    |W    |B    |B    |W    |',
 '   16 | MIKE NIKITIN                    |4.0  |D  10|W  15|H    |W  39|L   2|W  36|U    |',
 '   MI | 10295068 / R: 1604   ->1613     |N:3  |B    |W    |     |B    |W    |B    |     |',
 '   17 | RONALD GRZEGORCZYK              |4.0  |W  48|W  41|L  26|L   2|W  23|W  22|L   5|',
 '   MI | 10297702 / R: 1629   ->1610     |N:3  |W    |B    |W    |B    |W    |B    |W    |',
 '   18 | DAVID SUNDEEN                   |4.0  |W  47|W   9|L   1|W  32|L  19|W  38|L  10|',
 '   MI | 11342094 / R: 1600   ->1600     |N:3  |B    |W    |B    |W    |B    |W    |B    |',
 '   19 | DIPANKAR ROY                    |4.0  |D  15|W  10|W  52|D  28|W  18|L   4|L   8|',
 '   MI | 14862333 / R: 1564   ->1570     |N:3  |W    |B    |W    |B    |W    |W    |B    |',
 '   20 | JASON ZHENG                     |4.0  |L  40|W  49|W  23|W  41|W  28|L   2|L   9|',
 '   MI | 14529060 / R: 1595   ->1569     |N:4  |W    |B    |W    |B    |W    |B    |W    |',
 '   21 | DINH DANG BUI                   |4.0  |W  43|L   1|W  47|L   3|W  40|W  39|L   6|',
 '   ON | 15495066 / R: 1563P22->1562     |N:3  |B    |W    |B    |W    |W    |B    |W    |',
 '   22 | EUGENE L MCCLURE                |4.0  |W  64|D  52|L  28|W  15|H    |L  17|W  40|',
 '   MI | 12405534 / R: 1555   ->1529     |N:4  |W    |B    |W    |B    |     |W    |B    |',
 '   23 | ALAN BUI                        |4.0  |L   4|W  43|L  20|W  58|L  17|W  37|W  46|',
 '   ON | 15030142 / R: 1363   ->1371     |     |B    |W    |B    |W    |B    |W    |B    |',
 '   24 | MICHAEL R ALDRICH               |4.0  |L  28|L  47|W  43|L  25|W  60|W  44|W  39|',
 '   MI | 13469010 / R: 1229   ->1300     |N:4  |B    |W    |B    |B    |W    |W    |B    |',
 '   25 | LOREN SCHWIEBERT                |3.5  |L   9|W  53|L   3|W  24|D  34|L  10|W  47|',
 '   MI | 12486656 / R: 1745   ->1681     |N:4  |B    |W    |B    |W    |B    |W    |B    |',
 '   26 | MAX ZHU                         |3.5  |W  49|W  40|W  17|L   4|L   9|D  32|L  11|',
 '   ON | 15131520 / R: 1579   ->1564     |N:4  |B    |W    |B    |W    |B    |W    |W    |',
 '   27 | GAURAV GIDWANI                  |3.5  |W  51|L  13|W  46|W  37|D  14|L   6|U    |',
 '   MI | 14476567 / R: 1552   ->1539     |N:4  |W    |B    |W    |B    |W    |B    |     |',
 '   28 | SOFIA ADINA STANESCU-BELLU      |3.5  |W  24|D   4|W  22|D  19|L  20|L   8|D  36|',
 '   MI | 14882954 / R: 1507   ->1513     |N:3  |W    |W    |B    |W    |B    |B    |W    |',
 '   29 | CHIEDOZIE OKORIE                |3.5  |W  50|D   6|L  38|L  34|W  52|W  48|U    |',
 '   MI | 15323285 / R: 1602P6 ->1508P12  |N:4  |B    |W    |B    |W    |W    |B    |     |',
 '   30 | GEORGE AVERY JONES              |3.5  |L  52|D  64|L  15|W  55|L  31|W  61|W  50|',
 '   ON | 12577178 / R: 1522   ->1444     |     |W    |B    |B    |W    |W    |B    |B    |',
 '   31 | RISHI SHETTY                    |3.5  |L  58|D  55|W  64|L  10|W  30|W  50|L  14|',
 '   MI | 15131618 / R: 1494   ->1444     |     |B    |W    |B    |W    |B    |W    |B    |',
 '   32 | JOSHUA PHILIP MATHEWS           |3.5  |W  61|L   8|W  44|L  18|W  51|D  26|L  13|',
 '   ON | 14073750 / R: 1441   ->1433     |N:4  |W    |B    |W    |B    |W    |B    |W    |',
 '   33 | JADE GE                         |3.5  |W  60|L  12|W  50|D  36|L  13|L  15|W  51|',
 '   MI | 14691842 / R: 1449   ->1421     |     |B    |W    |B    |W    |B    |W    |B    |',
 '   34 | MICHAEL JEFFERY THOMAS          |3.5  |L   6|W  60|L  37|W  29|D  25|L  11|W  52|',
 '   MI | 15051807 / R: 1399   ->1400     |     |B    |W    |B    |B    |W    |B    |W    |',
 '   35 | JOSHUA DAVID LEE                |3.5  |L  46|L  38|W  56|L   6|W  57|D  52|W  48|',
 '   MI | 14601397 / R: 1438   ->1392     |     |W    |W    |B    |W    |B    |B    |W    |',
 '   36 | SIDDHARTH JHA                   |3.5  |L  13|W  57|W  51|D  33|H    |L  16|D  28|',
 '   MI | 14773163 / R: 1355   ->1367     |N:4  |W    |B    |W    |B    |     |W    |B    |',
 '   37 | AMIYATOSH PWNANANDAM            |3.5  |B    |L   5|W  34|L  27|H    |L  23|W  61|',
 '   MI | 15489571 / R:  980P12->1077P17  |     |     |B    |W    |W    |     |B    |W    |',
 '   38 | BRIAN LIU                       |3.0  |D  11|W  35|W  29|L  12|H    |L  18|L  15|',
 '   MI | 15108523 / R: 1423   ->1439     |N:4  |W    |B    |W    |W    |     |B    |B    |',
 '   39 | JOEL R HENDON                   |3.0  |L   1|W  54|W  40|L  16|W  44|L  21|L  24|',
 '   MI | 12923035 / R: 1436P23->1413     |N:4  |B    |W    |B    |W    |B    |W    |W    |',
 '   40 | FOREST ZHANG                    |3.0  |W  20|L  26|L  39|W  59|L  21|W  56|L  22|',
 '   MI | 14892710 / R: 1348   ->1346     |     |B    |B    |W    |W    |B    |W    |W    |',
 '   41 | KYLE WILLIAM MURPHY             |3.0  |W  59|L  17|W  58|L  20|X    |U    |U    |',
 '   MI | 15761443 / R: 1403P5 ->1341P9   |     |B    |W    |B    |W    |     |     |     |',
 '   42 | JARED GE                        |3.0  |L  12|L  50|L  57|D  60|D  61|W  64|W  56|',
 '   MI | 14462326 / R: 1332   ->1256     |     |B    |W    |B    |B    |W    |W    |B    |',
 '   43 | ROBERT GLEN VASEY               |3.0  |L  21|L  23|L  24|W  63|W  59|L  46|W  55|',
 '   MI | 14101068 / R: 1283   ->1244     |     |W    |B    |W    |W    |B    |B    |W    |',
 '   44 | JUSTIN D SCHILLING              |3.0  |B    |L  14|L  32|W  53|L  39|L  24|W  59|',
 '   MI | 15323504 / R: 1199   ->1199     |     |     |W    |B    |B    |W    |B    |W    |',
 '   45 | DEREK YAN                       |3.0  |L   5|L  51|D  60|L  56|W  63|D  55|W  58|',
 '   MI | 15372807 / R: 1242   ->1191     |     |W    |B    |W    |B    |W    |B    |W    |',
 '   46 | JACOB ALEXANDER LAVALLEY        |3.0  |W  35|L   7|L  27|L  50|W  64|W  43|L  23|',
 '   MI | 15490981 / R:  377P3 ->1076P10  |     |B    |W    |B    |W    |B    |W    |W    |',
 '   47 | ERIC WRIGHT                     |2.5  |L  18|W  24|L  21|W  61|L   8|D  51|L  25|',
 '   MI | 12533115 / R: 1362   ->1341     |     |W    |B    |W    |B    |W    |B    |W    |',
 '   48 | DANIEL KHAIN                    |2.5  |L  17|W  63|H    |D  52|H    |L  29|L  35|',
 '   MI | 14369165 / R: 1382   ->1335     |     |B    |W    |     |B    |     |W    |B    |',
 '   49 | MICHAEL J MARTIN                |2.5  |L  26|L  20|D  63|D  64|W  58|H    |U    |',
 '   MI | 12531685 / R: 1291P12->1259P17  |     |W    |W    |B    |W    |B    |     |     |',
 '   50 | SHIVAM JHA                      |2.5  |L  29|W  42|L  33|W  46|H    |L  31|L  30|',
 '   MI | 14773178 / R: 1056   ->1111     |     |W    |B    |W    |B    |     |B    |W    |',
 '   51 | TEJAS AYYAGARI                  |2.5  |L  27|W  45|L  36|W  57|L  32|D  47|L  33|',
 '   MI | 15205474 / R: 1011   ->1097     |     |B    |W    |B    |W    |B    |W    |W    |',
 '   52 | ETHAN GUO                       |2.5  |W  30|D  22|L  19|D  48|L  29|D  35|L  34|',
 '   MI | 14918803 / R:  935   ->1092     |N:4  |B    |W    |B    |W    |B    |W    |B    |',
 '   53 | JOSE C YBARRA                   |2.0  |H    |L  25|H    |L  44|U    |W  57|U    |',
 '   MI | 12578849 / R: 1393   ->1359     |     |     |B    |     |W    |     |W    |     |',
 '   54 | LARRY HODGE                     |2.0  |L  14|L  39|L  61|B    |L  15|L  59|W  64|',
 '   MI | 12836773 / R: 1270   ->1200     |     |B    |B    |W    |     |W    |B    |W    |',
 '   55 | ALEX KONG                       |2.0  |L  62|D  31|L  10|L  30|B    |D  45|L  43|',
 '   MI | 15412571 / R: 1186   ->1163     |     |W    |B    |W    |B    |     |W    |B    |',
 '   56 | MARISA RICCI                    |2.0  |H    |L  11|L  35|W  45|H    |L  40|L  42|',
 '   MI | 14679887 / R: 1153   ->1140     |     |     |B    |W    |W    |     |B    |W    |',
 '   57 | MICHAEL LU                      |2.0  |L   7|L  36|W  42|L  51|L  35|L  53|B    |',
 '   MI | 15113330 / R: 1092   ->1079     |     |B    |W    |W    |B    |W    |B    |     |',
 '   58 | VIRAJ MOHILE                    |2.0  |W  31|L   2|L  41|L  23|L  49|B    |L  45|',
 '   MI | 14700365 / R:  917   -> 941     |     |W    |B    |W    |B    |W    |     |B    |',
 '   59 | SEAN M MC CORMICK               |2.0  |L  41|B    |L   9|L  40|L  43|W  54|L  44|',
 '   MI | 12841036 / R:  853   -> 878     |     |W    |     |B    |B    |W    |W    |B    |',
 '   60 | JULIA SHEN                      |1.5  |L  33|L  34|D  45|D  42|L  24|H    |U    |',
 '   MI | 14579262 / R:  967   -> 984     |     |W    |B    |B    |W    |B    |     |     |',
 '   61 | JEZZEL FARKAS                   |1.5  |L  32|L   3|W  54|L  47|D  42|L  30|L  37|',
 '   ON | 15771592 / R:  955P11-> 979P18  |     |B    |W    |B    |W    |B    |W    |B    |',
 '   62 | ASHWIN BALAJI                   |1.0  |W  55|U    |U    |U    |U    |U    |U    |',
 '   MI | 15219542 / R: 1530   ->1535     |     |B    |     |     |     |     |     |     |',
 '   63 | THOMAS JOSEPH HOSMER            |1.0  |L   2|L  48|D  49|L  43|L  45|H    |U    |',
 '   MI | 15057092 / R: 1175   ->1125     |     |W    |B    |W    |B    |B    |     |     |',
 '   64 | BEN LI                          |1.0  |L  22|D  30|L  31|D  49|L  46|L  42|L  54|',
 '   MI | 15006561 / R: 1163   ->1112     |     |B    |W    |W    |B    |W    |B    |B    |']

We now have the list of every line storing players' information. We will next extract the required information.

In [5]:
# create an empty list before looping
# turn each line into string the utilize regex formula
# use regex findall function to get names 
# append it into the new list

names_1 = []

for i in chess_2:
    i = str(i)
    names_1.append(re.compile("\|\s[A-Z][A-Z\s]+").findall(i))
    
# check
names_1

[[],
 ['| USCF ID '],
 ['| GARY HUA                        '],
 [],
 ['| DAKSHESH DARURI                 '],
 [],
 ['| ADITYA BAJAJ                    '],
 [],
 ['| PATRICK H SCHILLING             '],
 [],
 ['| HANSHI ZUO                      '],
 [],
 ['| HANSEN SONG                     '],
 [],
 ['| GARY DEE SWATHELL               '],
 [],
 ['| EZEKIEL HOUGHTON                '],
 [],
 ['| STEFANO LEE                     '],
 [],
 ['| ANVIT RAO                       '],
 [],
 ['| CAMERON WILLIAM MC LEMAN        '],
 [],
 ['| KENNETH J TACK                  '],
 [],
 ['| TORRANCE HENRY JR               '],
 [],
 ['| BRADLEY SHAW                    '],
 [],
 ['| ZACHARY JAMES HOUGHTON          '],
 [],
 ['| MIKE NIKITIN                    '],
 [],
 ['| RONALD GRZEGORCZYK              '],
 [],
 ['| DAVID SUNDEEN                   '],
 [],
 ['| DIPANKAR ROY                    '],
 [],
 ['| JASON ZHENG                     '],
 [],
 ['| DINH DANG BUI                   '],
 [],
 ['| EUGENE L MCCLURE                '],
 [],
 ['| ALAN BUI                        '],
 [],
 ['| MICHAEL R ALDRICH               '],
 [],
 ['| LOREN SCHWIEBERT                '],
 [],
 ['| MAX ZHU                         '],
 [],
 ['| GAURAV GIDWANI                  '],
 [],
 ['| SOFIA ADINA STANESCU'],
 [],
 ['| CHIEDOZIE OKORIE                '],
 [],
 ['| GEORGE AVERY JONES              '],
 [],
 ['| RISHI SHETTY                    '],
 [],
 ['| JOSHUA PHILIP MATHEWS           '],
 [],
 ['| JADE GE                         '],
 [],
 ['| MICHAEL JEFFERY THOMAS          '],
 [],
 ['| JOSHUA DAVID LEE                '],
 [],
 ['| SIDDHARTH JHA                   '],
 [],
 ['| AMIYATOSH PWNANANDAM            '],
 [],
 ['| BRIAN LIU                       '],
 [],
 ['| JOEL R HENDON                   '],
 [],
 ['| FOREST ZHANG                    '],
 [],
 ['| KYLE WILLIAM MURPHY             '],
 [],
 ['| JARED GE                        '],
 [],
 ['| ROBERT GLEN VASEY               '],
 [],
 ['| JUSTIN D SCHILLING              '],
 [],
 ['| DEREK YAN                       '],
 [],
 ['| JACOB ALEXANDER LAVALLEY        '],
 [],
 ['| ERIC WRIGHT                     '],
 [],
 ['| DANIEL KHAIN                    '],
 [],
 ['| MICHAEL J MARTIN                '],
 [],
 ['| SHIVAM JHA                      '],
 [],
 ['| TEJAS AYYAGARI                  '],
 [],
 ['| ETHAN GUO                       '],
 [],
 ['| JOSE C YBARRA                   '],
 [],
 ['| LARRY HODGE                     '],
 [],
 ['| ALEX KONG                       '],
 [],
 ['| MARISA RICCI                    '],
 [],
 ['| MICHAEL LU                      '],
 [],
 ['| VIRAJ MOHILE                    '],
 [],
 ['| SEAN M MC CORMICK               '],
 [],
 ['| JULIA SHEN                      '],
 [],
 ['| JEZZEL FARKAS                   '],
 [],
 ['| ASHWIN BALAJI                   '],
 [],
 ['| THOMAS JOSEPH HOSMER            '],
 [],
 ['| BEN LI                          '],
 []]

As it is clear that the first two lines of the list has nothing to with our analysis. Additionally, there are empty elements in the list. We will remove them.

In [6]:
# the first two elements will no be included
names_1 = names_1[2:]

# remove empty elements in the list using remove method
for i in names_1:
    if i == []:
        names_1.remove(i)
        
names_1

[['| GARY HUA                        '],
 ['| DAKSHESH DARURI                 '],
 ['| ADITYA BAJAJ                    '],
 ['| PATRICK H SCHILLING             '],
 ['| HANSHI ZUO                      '],
 ['| HANSEN SONG                     '],
 ['| GARY DEE SWATHELL               '],
 ['| EZEKIEL HOUGHTON                '],
 ['| STEFANO LEE                     '],
 ['| ANVIT RAO                       '],
 ['| CAMERON WILLIAM MC LEMAN        '],
 ['| KENNETH J TACK                  '],
 ['| TORRANCE HENRY JR               '],
 ['| BRADLEY SHAW                    '],
 ['| ZACHARY JAMES HOUGHTON          '],
 ['| MIKE NIKITIN                    '],
 ['| RONALD GRZEGORCZYK              '],
 ['| DAVID SUNDEEN                   '],
 ['| DIPANKAR ROY                    '],
 ['| JASON ZHENG                     '],
 ['| DINH DANG BUI                   '],
 ['| EUGENE L MCCLURE                '],
 ['| ALAN BUI                        '],
 ['| MICHAEL R ALDRICH               '],
 ['| LOREN SCHWIEBERT                '],
 ['| MAX ZHU                         '],
 ['| GAURAV GIDWANI                  '],
 ['| SOFIA ADINA STANESCU'],
 ['| CHIEDOZIE OKORIE                '],
 ['| GEORGE AVERY JONES              '],
 ['| RISHI SHETTY                    '],
 ['| JOSHUA PHILIP MATHEWS           '],
 ['| JADE GE                         '],
 ['| MICHAEL JEFFERY THOMAS          '],
 ['| JOSHUA DAVID LEE                '],
 ['| SIDDHARTH JHA                   '],
 ['| AMIYATOSH PWNANANDAM            '],
 ['| BRIAN LIU                       '],
 ['| JOEL R HENDON                   '],
 ['| FOREST ZHANG                    '],
 ['| KYLE WILLIAM MURPHY             '],
 ['| JARED GE                        '],
 ['| ROBERT GLEN VASEY               '],
 ['| JUSTIN D SCHILLING              '],
 ['| DEREK YAN                       '],
 ['| JACOB ALEXANDER LAVALLEY        '],
 ['| ERIC WRIGHT                     '],
 ['| DANIEL KHAIN                    '],
 ['| MICHAEL J MARTIN                '],
 ['| SHIVAM JHA                      '],
 ['| TEJAS AYYAGARI                  '],
 ['| ETHAN GUO                       '],
 ['| JOSE C YBARRA                   '],
 ['| LARRY HODGE                     '],
 ['| ALEX KONG                       '],
 ['| MARISA RICCI                    '],
 ['| MICHAEL LU                      '],
 ['| VIRAJ MOHILE                    '],
 ['| SEAN M MC CORMICK               '],
 ['| JULIA SHEN                      '],
 ['| JEZZEL FARKAS                   '],
 ['| ASHWIN BALAJI                   '],
 ['| THOMAS JOSEPH HOSMER            '],
 ['| BEN LI                          ']]

Now we should clean the names list by removing unnecessary spaces and '|' symbols using string strip() and regex sub() methods

In [7]:
# create an empty list before looping
# remove extra spaces using strip()
# remove '\' symbols using re.sub()
# Only capitals in the beginning of the words using title()


names_final = []

for i in names_1:
    for x in i:
        x = x.strip()
        names_final.append(re.sub('\| ','',x))
        names_final = [i.title() for i in names_final]

# check
names_final

['Gary Hua',
 'Dakshesh Daruri',
 'Aditya Bajaj',
 'Patrick H Schilling',
 'Hanshi Zuo',
 'Hansen Song',
 'Gary Dee Swathell',
 'Ezekiel Houghton',
 'Stefano Lee',
 'Anvit Rao',
 'Cameron William Mc Leman',
 'Kenneth J Tack',
 'Torrance Henry Jr',
 'Bradley Shaw',
 'Zachary James Houghton',
 'Mike Nikitin',
 'Ronald Grzegorczyk',
 'David Sundeen',
 'Dipankar Roy',
 'Jason Zheng',
 'Dinh Dang Bui',
 'Eugene L Mcclure',
 'Alan Bui',
 'Michael R Aldrich',
 'Loren Schwiebert',
 'Max Zhu',
 'Gaurav Gidwani',
 'Sofia Adina Stanescu',
 'Chiedozie Okorie',
 'George Avery Jones',
 'Rishi Shetty',
 'Joshua Philip Mathews',
 'Jade Ge',
 'Michael Jeffery Thomas',
 'Joshua David Lee',
 'Siddharth Jha',
 'Amiyatosh Pwnanandam',
 'Brian Liu',
 'Joel R Hendon',
 'Forest Zhang',
 'Kyle William Murphy',
 'Jared Ge',
 'Robert Glen Vasey',
 'Justin D Schilling',
 'Derek Yan',
 'Jacob Alexander Lavalley',
 'Eric Wright',
 'Daniel Khain',
 'Michael J Martin',
 'Shivam Jha',
 'Tejas Ayyagari',
 'Ethan Guo',
 'Jose C Ybarra',
 'Larry Hodge',
 'Alex Kong',
 'Marisa Ricci',
 'Michael Lu',
 'Viraj Mohile',
 'Sean M Mc Cormick',
 'Julia Shen',
 'Jezzel Farkas',
 'Ashwin Balaji',
 'Thomas Joseph Hosmer',
 'Ben Li']

#### Step 2: We will now extract total points of the players using looping and a regex formula.

In [10]:
# create an empty list to append the points
# loope and turn each item a string to utilize regex
# use regex to extract data

total_point = []

for num in chess_2:
    num = str(num)
    total_point.append(re.compile("\d\.\d").findall(num))
    
    # remove empty lists using remove() function
for point in total_point:
    if point == []:
        total_point.remove(point)
            
# check
total_point

[['6.0'],
 ['6.0'],
 ['6.0'],
 ['5.5'],
 ['5.5'],
 ['5.0'],
 ['5.0'],
 ['5.0'],
 ['5.0'],
 ['5.0'],
 ['4.5'],
 ['4.5'],
 ['4.5'],
 ['4.5'],
 ['4.5'],
 ['4.0'],
 ['4.0'],
 ['4.0'],
 ['4.0'],
 ['4.0'],
 ['4.0'],
 ['4.0'],
 ['4.0'],
 ['4.0'],
 ['3.5'],
 ['3.5'],
 ['3.5'],
 ['3.5'],
 ['3.5'],
 ['3.5'],
 ['3.5'],
 ['3.5'],
 ['3.5'],
 ['3.5'],
 ['3.5'],
 ['3.5'],
 ['3.5'],
 ['3.0'],
 ['3.0'],
 ['3.0'],
 ['3.0'],
 ['3.0'],
 ['3.0'],
 ['3.0'],
 ['3.0'],
 ['3.0'],
 ['2.5'],
 ['2.5'],
 ['2.5'],
 ['2.5'],
 ['2.5'],
 ['2.5'],
 ['2.0'],
 ['2.0'],
 ['2.0'],
 ['2.0'],
 ['2.0'],
 ['2.0'],
 ['2.0'],
 ['1.5'],
 ['1.5'],
 ['1.0'],
 ['1.0'],
 ['1.0'],
 []]

In [12]:
# get rid of the nested lists
# create an emtpy list to append
# turn each item into float

total_point_final = []

for num in total_point:
    for item in num:
        total_point_final.append(float(item))


# check
total_point_final

[6.0,
 6.0,
 6.0,
 5.5,
 5.5,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 4.5,
 4.5,
 4.5,
 4.5,
 4.5,
 4.0,
 4.0,
 4.0,
 4.0,
 4.0,
 4.0,
 4.0,
 4.0,
 4.0,
 3.5,
 3.5,
 3.5,
 3.5,
 3.5,
 3.5,
 3.5,
 3.5,
 3.5,
 3.5,
 3.5,
 3.5,
 3.5,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 2.5,
 2.5,
 2.5,
 2.5,
 2.5,
 2.5,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 1.5,
 1.5,
 1.0,
 1.0,
 1.0]

In [13]:
# check the length of the lists

len(names_final)

64

In [14]:
len(total_point_final)

64

## Task 2: To extract the information (state and pre-tournament rating) from the second line for each player:

### Step 1: We have 64 items in names and points list. We next get the state data using the same method.

In [15]:
state = []
state_final = []

for item in chess_2:
    state.append(re.compile("\s\s[A-Z]{2}\s").findall(str(item)))
    


for item in state:
    for i in item:
        state_final.append(i.strip()) # remove extra spaces

# check
state_final

['ON',
 'MI',
 'MI',
 'MI',
 'MI',
 'OH',
 'MI',
 'MI',
 'ON',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'ON',
 'MI',
 'ON',
 'MI',
 'MI',
 'ON',
 'MI',
 'MI',
 'MI',
 'ON',
 'MI',
 'ON',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'ON',
 'MI',
 'MI',
 'MI']

In [16]:
len(state_final)

64

State list has also 64 items in it.

### Step 2: To extract pre-tournament rating of each player

In [17]:
pre_tournament_rating_1 = []

for i in chess_2:
    pre_tournament_rating_1.append(re.compile("R:\s[0-9]{4}|R:\s\s[0-9]{3}").findall(str(i)))


pre_tournament_rating_2 = []

for i in pre_tournament_rating_1:
    for x in i:
        pre_tournament_rating_2.append(x.strip())

pre_tournament_rating_3 = []
for i in pre_tournament_rating_2:
    pre_tournament_rating_3.append(re.sub('R:\s','', i)) 

pre_tournament_rating_3

['1794',
 '1553',
 '1384',
 '1716',
 '1655',
 '1686',
 '1649',
 '1641',
 '1411',
 '1365',
 '1712',
 '1663',
 '1666',
 '1610',
 '1220',
 '1604',
 '1629',
 '1600',
 '1564',
 '1595',
 '1563',
 '1555',
 '1363',
 '1229',
 '1745',
 '1579',
 '1552',
 '1507',
 '1602',
 '1522',
 '1494',
 '1441',
 '1449',
 '1399',
 '1438',
 '1355',
 ' 980',
 '1423',
 '1436',
 '1348',
 '1403',
 '1332',
 '1283',
 '1199',
 '1242',
 ' 377',
 '1362',
 '1382',
 '1291',
 '1056',
 '1011',
 ' 935',
 '1393',
 '1270',
 '1186',
 '1153',
 '1092',
 ' 917',
 ' 853',
 ' 967',
 ' 955',
 '1530',
 '1175',
 '1163']

In [18]:
# removing extra spaces and stroing the final version

ptr_final = []
for i in pre_tournament_rating_3:
    ptr_final.append(i.strip())
    
ptr_final

['1794',
 '1553',
 '1384',
 '1716',
 '1655',
 '1686',
 '1649',
 '1641',
 '1411',
 '1365',
 '1712',
 '1663',
 '1666',
 '1610',
 '1220',
 '1604',
 '1629',
 '1600',
 '1564',
 '1595',
 '1563',
 '1555',
 '1363',
 '1229',
 '1745',
 '1579',
 '1552',
 '1507',
 '1602',
 '1522',
 '1494',
 '1441',
 '1449',
 '1399',
 '1438',
 '1355',
 '980',
 '1423',
 '1436',
 '1348',
 '1403',
 '1332',
 '1283',
 '1199',
 '1242',
 '377',
 '1362',
 '1382',
 '1291',
 '1056',
 '1011',
 '935',
 '1393',
 '1270',
 '1186',
 '1153',
 '1092',
 '917',
 '853',
 '967',
 '955',
 '1530',
 '1175',
 '1163']

In [19]:
len(ptr_final)

64

Pre-tournament ratings has also 64 elements. Finally we will extract the Average Pre Tournament Chess Rating of Opponents data. Here are the steps we will follow for that task:

- Extract the data in the rows using regex
- Extract only numbers from it ans store in a list as integers, since each value will be used as index value
- Get the opponents pre-tournament ratings in a list using the extracted numbers as indices and store them in a list
- Finally, get the average of each list in the list and store them

## Task 3: To calculate and process the average pre-tournament rating of each  player’s opponents.

In [20]:
# create an emty list
# the first two rows do not include any dat, skip them, and iterate over every second line
# use regex to extract the relevant parts in the rows
# store them in the new list

rounds_1 = []

for i in range(2, len(chess_2), 2):
    rounds_1.append(re.compile("\|\w\s{2,3}\d{1,2}|\|\w\s{4}").findall(str(chess_2[i])))
rounds_1

[['|W  39', '|W  21', '|W  18', '|W  14', '|W   7', '|D  12', '|D   4'],
 ['|W  63', '|W  58', '|L   4', '|W  17', '|W  16', '|W  20', '|W   7'],
 ['|L   8', '|W  61', '|W  25', '|W  21', '|W  11', '|W  13', '|W  12'],
 ['|W  23', '|D  28', '|W   2', '|W  26', '|D   5', '|W  19', '|D   1'],
 ['|W  45', '|W  37', '|D  12', '|D  13', '|D   4', '|W  14', '|W  17'],
 ['|W  34', '|D  29', '|L  11', '|W  35', '|D  10', '|W  27', '|W  21'],
 ['|W  57', '|W  46', '|W  13', '|W  11', '|L   1', '|W   9', '|L   2'],
 ['|W   3', '|W  32', '|L  14', '|L   9', '|W  47', '|W  28', '|W  19'],
 ['|W  25', '|L  18', '|W  59', '|W   8', '|W  26', '|L   7', '|W  20'],
 ['|D  16', '|L  19', '|W  55', '|W  31', '|D   6', '|W  25', '|W  18'],
 ['|D  38', '|W  56', '|W   6', '|L   7', '|L   3', '|W  34', '|W  26'],
 ['|W  42', '|W  33', '|D   5', '|W  38', '|H    ', '|D   1', '|L   3'],
 ['|W  36', '|W  27', '|L   7', '|D   5', '|W  33', '|L   3', '|W  32'],
 ['|W  54', '|W  44', '|W   8', '|L   1', '|D  27', '|L   5', '|W  31'],
 ['|D  19', '|L  16', '|W  30', '|L  22', '|W  54', '|W  33', '|W  38'],
 ['|D  10', '|W  15', '|H    ', '|W  39', '|L   2', '|W  36', '|U    '],
 ['|W  48', '|W  41', '|L  26', '|L   2', '|W  23', '|W  22', '|L   5'],
 ['|W  47', '|W   9', '|L   1', '|W  32', '|L  19', '|W  38', '|L  10'],
 ['|D  15', '|W  10', '|W  52', '|D  28', '|W  18', '|L   4', '|L   8'],
 ['|L  40', '|W  49', '|W  23', '|W  41', '|W  28', '|L   2', '|L   9'],
 ['|W  43', '|L   1', '|W  47', '|L   3', '|W  40', '|W  39', '|L   6'],
 ['|W  64', '|D  52', '|L  28', '|W  15', '|H    ', '|L  17', '|W  40'],
 ['|L   4', '|W  43', '|L  20', '|W  58', '|L  17', '|W  37', '|W  46'],
 ['|L  28', '|L  47', '|W  43', '|L  25', '|W  60', '|W  44', '|W  39'],
 ['|L   9', '|W  53', '|L   3', '|W  24', '|D  34', '|L  10', '|W  47'],
 ['|W  49', '|W  40', '|W  17', '|L   4', '|L   9', '|D  32', '|L  11'],
 ['|W  51', '|L  13', '|W  46', '|W  37', '|D  14', '|L   6', '|U    '],
 ['|W  24', '|D   4', '|W  22', '|D  19', '|L  20', '|L   8', '|D  36'],
 ['|W  50', '|D   6', '|L  38', '|L  34', '|W  52', '|W  48', '|U    '],
 ['|L  52', '|D  64', '|L  15', '|W  55', '|L  31', '|W  61', '|W  50'],
 ['|L  58', '|D  55', '|W  64', '|L  10', '|W  30', '|W  50', '|L  14'],
 ['|W  61', '|L   8', '|W  44', '|L  18', '|W  51', '|D  26', '|L  13'],
 ['|W  60', '|L  12', '|W  50', '|D  36', '|L  13', '|L  15', '|W  51'],
 ['|L   6', '|W  60', '|L  37', '|W  29', '|D  25', '|L  11', '|W  52'],
 ['|L  46', '|L  38', '|W  56', '|L   6', '|W  57', '|D  52', '|W  48'],
 ['|L  13', '|W  57', '|W  51', '|D  33', '|H    ', '|L  16', '|D  28'],
 ['|B    ', '|L   5', '|W  34', '|L  27', '|H    ', '|L  23', '|W  61'],
 ['|D  11', '|W  35', '|W  29', '|L  12', '|H    ', '|L  18', '|L  15'],
 ['|L   1', '|W  54', '|W  40', '|L  16', '|W  44', '|L  21', '|L  24'],
 ['|W  20', '|L  26', '|L  39', '|W  59', '|L  21', '|W  56', '|L  22'],
 ['|W  59', '|L  17', '|W  58', '|L  20', '|X    ', '|U    ', '|U    '],
 ['|L  12', '|L  50', '|L  57', '|D  60', '|D  61', '|W  64', '|W  56'],
 ['|L  21', '|L  23', '|L  24', '|W  63', '|W  59', '|L  46', '|W  55'],
 ['|B    ', '|L  14', '|L  32', '|W  53', '|L  39', '|L  24', '|W  59'],
 ['|L   5', '|L  51', '|D  60', '|L  56', '|W  63', '|D  55', '|W  58'],
 ['|W  35', '|L   7', '|L  27', '|L  50', '|W  64', '|W  43', '|L  23'],
 ['|L  18', '|W  24', '|L  21', '|W  61', '|L   8', '|D  51', '|L  25'],
 ['|L  17', '|W  63', '|H    ', '|D  52', '|H    ', '|L  29', '|L  35'],
 ['|L  26', '|L  20', '|D  63', '|D  64', '|W  58', '|H    ', '|U    '],
 ['|L  29', '|W  42', '|L  33', '|W  46', '|H    ', '|L  31', '|L  30'],
 ['|L  27', '|W  45', '|L  36', '|W  57', '|L  32', '|D  47', '|L  33'],
 ['|W  30', '|D  22', '|L  19', '|D  48', '|L  29', '|D  35', '|L  34'],
 ['|H    ', '|L  25', '|H    ', '|L  44', '|U    ', '|W  57', '|U    '],
 ['|L  14', '|L  39', '|L  61', '|B    ', '|L  15', '|L  59', '|W  64'],
 ['|L  62', '|D  31', '|L  10', '|L  30', '|B    ', '|D  45', '|L  43'],
 ['|H    ', '|L  11', '|L  35', '|W  45', '|H    ', '|L  40', '|L  42'],
 ['|L   7', '|L  36', '|W  42', '|L  51', '|L  35', '|L  53', '|B    '],
 ['|W  31', '|L   2', '|L  41', '|L  23', '|L  49', '|B    ', '|L  45'],
 ['|L  41', '|B    ', '|L   9', '|L  40', '|L  43', '|W  54', '|L  44'],
 ['|L  33', '|L  34', '|D  45', '|D  42', '|L  24', '|H    ', '|U    '],
 ['|L  32', '|L   3', '|W  54', '|L  47', '|D  42', '|L  30', '|L  37'],
 ['|W  55', '|U    ', '|U    ', '|U    ', '|U    ', '|U    ', '|U    '],
 ['|L   2', '|L  48', '|D  49', '|L  43', '|L  45', '|H    ', '|U    '],
 ['|L  22', '|D  30', '|L  31', '|D  49', '|L  46', '|L  42', '|L  54']]

We need to get rid of letters, spaces and '\' symbols. To do that we will use another regex formula and store the data in a list.

In [21]:
rounds_2 = []

for i in rounds_1:
    rounds_2.append(re.compile("\d{1,2}").findall(str(i)))
    
rounds_2

[['39', '21', '18', '14', '7', '12', '4'],
 ['63', '58', '4', '17', '16', '20', '7'],
 ['8', '61', '25', '21', '11', '13', '12'],
 ['23', '28', '2', '26', '5', '19', '1'],
 ['45', '37', '12', '13', '4', '14', '17'],
 ['34', '29', '11', '35', '10', '27', '21'],
 ['57', '46', '13', '11', '1', '9', '2'],
 ['3', '32', '14', '9', '47', '28', '19'],
 ['25', '18', '59', '8', '26', '7', '20'],
 ['16', '19', '55', '31', '6', '25', '18'],
 ['38', '56', '6', '7', '3', '34', '26'],
 ['42', '33', '5', '38', '1', '3'],
 ['36', '27', '7', '5', '33', '3', '32'],
 ['54', '44', '8', '1', '27', '5', '31'],
 ['19', '16', '30', '22', '54', '33', '38'],
 ['10', '15', '39', '2', '36'],
 ['48', '41', '26', '2', '23', '22', '5'],
 ['47', '9', '1', '32', '19', '38', '10'],
 ['15', '10', '52', '28', '18', '4', '8'],
 ['40', '49', '23', '41', '28', '2', '9'],
 ['43', '1', '47', '3', '40', '39', '6'],
 ['64', '52', '28', '15', '17', '40'],
 ['4', '43', '20', '58', '17', '37', '46'],
 ['28', '47', '43', '25', '60', '44', '39'],
 ['9', '53', '3', '24', '34', '10', '47'],
 ['49', '40', '17', '4', '9', '32', '11'],
 ['51', '13', '46', '37', '14', '6'],
 ['24', '4', '22', '19', '20', '8', '36'],
 ['50', '6', '38', '34', '52', '48'],
 ['52', '64', '15', '55', '31', '61', '50'],
 ['58', '55', '64', '10', '30', '50', '14'],
 ['61', '8', '44', '18', '51', '26', '13'],
 ['60', '12', '50', '36', '13', '15', '51'],
 ['6', '60', '37', '29', '25', '11', '52'],
 ['46', '38', '56', '6', '57', '52', '48'],
 ['13', '57', '51', '33', '16', '28'],
 ['5', '34', '27', '23', '61'],
 ['11', '35', '29', '12', '18', '15'],
 ['1', '54', '40', '16', '44', '21', '24'],
 ['20', '26', '39', '59', '21', '56', '22'],
 ['59', '17', '58', '20'],
 ['12', '50', '57', '60', '61', '64', '56'],
 ['21', '23', '24', '63', '59', '46', '55'],
 ['14', '32', '53', '39', '24', '59'],
 ['5', '51', '60', '56', '63', '55', '58'],
 ['35', '7', '27', '50', '64', '43', '23'],
 ['18', '24', '21', '61', '8', '51', '25'],
 ['17', '63', '52', '29', '35'],
 ['26', '20', '63', '64', '58'],
 ['29', '42', '33', '46', '31', '30'],
 ['27', '45', '36', '57', '32', '47', '33'],
 ['30', '22', '19', '48', '29', '35', '34'],
 ['25', '44', '57'],
 ['14', '39', '61', '15', '59', '64'],
 ['62', '31', '10', '30', '45', '43'],
 ['11', '35', '45', '40', '42'],
 ['7', '36', '42', '51', '35', '53'],
 ['31', '2', '41', '23', '49', '45'],
 ['41', '9', '40', '43', '54', '44'],
 ['33', '34', '45', '42', '24'],
 ['32', '3', '54', '47', '42', '30', '37'],
 ['55'],
 ['2', '48', '49', '43', '45'],
 ['22', '30', '31', '49', '46', '42', '54']]

In [22]:
# turn items into integer

rounds_final = [[int(i) for i in lst] for lst in rounds_2]

# check
rounds_final

[[39, 21, 18, 14, 7, 12, 4],
 [63, 58, 4, 17, 16, 20, 7],
 [8, 61, 25, 21, 11, 13, 12],
 [23, 28, 2, 26, 5, 19, 1],
 [45, 37, 12, 13, 4, 14, 17],
 [34, 29, 11, 35, 10, 27, 21],
 [57, 46, 13, 11, 1, 9, 2],
 [3, 32, 14, 9, 47, 28, 19],
 [25, 18, 59, 8, 26, 7, 20],
 [16, 19, 55, 31, 6, 25, 18],
 [38, 56, 6, 7, 3, 34, 26],
 [42, 33, 5, 38, 1, 3],
 [36, 27, 7, 5, 33, 3, 32],
 [54, 44, 8, 1, 27, 5, 31],
 [19, 16, 30, 22, 54, 33, 38],
 [10, 15, 39, 2, 36],
 [48, 41, 26, 2, 23, 22, 5],
 [47, 9, 1, 32, 19, 38, 10],
 [15, 10, 52, 28, 18, 4, 8],
 [40, 49, 23, 41, 28, 2, 9],
 [43, 1, 47, 3, 40, 39, 6],
 [64, 52, 28, 15, 17, 40],
 [4, 43, 20, 58, 17, 37, 46],
 [28, 47, 43, 25, 60, 44, 39],
 [9, 53, 3, 24, 34, 10, 47],
 [49, 40, 17, 4, 9, 32, 11],
 [51, 13, 46, 37, 14, 6],
 [24, 4, 22, 19, 20, 8, 36],
 [50, 6, 38, 34, 52, 48],
 [52, 64, 15, 55, 31, 61, 50],
 [58, 55, 64, 10, 30, 50, 14],
 [61, 8, 44, 18, 51, 26, 13],
 [60, 12, 50, 36, 13, 15, 51],
 [6, 60, 37, 29, 25, 11, 52],
 [46, 38, 56, 6, 57, 52, 48],
 [13, 57, 51, 33, 16, 28],
 [5, 34, 27, 23, 61],
 [11, 35, 29, 12, 18, 15],
 [1, 54, 40, 16, 44, 21, 24],
 [20, 26, 39, 59, 21, 56, 22],
 [59, 17, 58, 20],
 [12, 50, 57, 60, 61, 64, 56],
 [21, 23, 24, 63, 59, 46, 55],
 [14, 32, 53, 39, 24, 59],
 [5, 51, 60, 56, 63, 55, 58],
 [35, 7, 27, 50, 64, 43, 23],
 [18, 24, 21, 61, 8, 51, 25],
 [17, 63, 52, 29, 35],
 [26, 20, 63, 64, 58],
 [29, 42, 33, 46, 31, 30],
 [27, 45, 36, 57, 32, 47, 33],
 [30, 22, 19, 48, 29, 35, 34],
 [25, 44, 57],
 [14, 39, 61, 15, 59, 64],
 [62, 31, 10, 30, 45, 43],
 [11, 35, 45, 40, 42],
 [7, 36, 42, 51, 35, 53],
 [31, 2, 41, 23, 49, 45],
 [41, 9, 40, 43, 54, 44],
 [33, 34, 45, 42, 24],
 [32, 3, 54, 47, 42, 30, 37],
 [55],
 [2, 48, 49, 43, 45],
 [22, 30, 31, 49, 46, 42, 54]]

In [23]:
# employing the above list as indices in the pre-tournament ratings list to get the list of opponents ratings
# there is one element difference between ptr_final and rounds_final list

opponents_lst = [[int(ptr_final[i-1]) for i in lst] for lst in rounds_final]
opponents_lst

[[1436, 1563, 1600, 1610, 1649, 1663, 1716],
 [1175, 917, 1716, 1629, 1604, 1595, 1649],
 [1641, 955, 1745, 1563, 1712, 1666, 1663],
 [1363, 1507, 1553, 1579, 1655, 1564, 1794],
 [1242, 980, 1663, 1666, 1716, 1610, 1629],
 [1399, 1602, 1712, 1438, 1365, 1552, 1563],
 [1092, 377, 1666, 1712, 1794, 1411, 1553],
 [1384, 1441, 1610, 1411, 1362, 1507, 1564],
 [1745, 1600, 853, 1641, 1579, 1649, 1595],
 [1604, 1564, 1186, 1494, 1686, 1745, 1600],
 [1423, 1153, 1686, 1649, 1384, 1399, 1579],
 [1332, 1449, 1655, 1423, 1794, 1384],
 [1355, 1552, 1649, 1655, 1449, 1384, 1441],
 [1270, 1199, 1641, 1794, 1552, 1655, 1494],
 [1564, 1604, 1522, 1555, 1270, 1449, 1423],
 [1365, 1220, 1436, 1553, 1355],
 [1382, 1403, 1579, 1553, 1363, 1555, 1655],
 [1362, 1411, 1794, 1441, 1564, 1423, 1365],
 [1220, 1365, 935, 1507, 1600, 1716, 1641],
 [1348, 1291, 1363, 1403, 1507, 1553, 1411],
 [1283, 1794, 1362, 1384, 1348, 1436, 1686],
 [1163, 935, 1507, 1220, 1629, 1348],
 [1716, 1283, 1595, 917, 1629, 980, 377],
 [1507, 1362, 1283, 1745, 967, 1199, 1436],
 [1411, 1393, 1384, 1229, 1399, 1365, 1362],
 [1291, 1348, 1629, 1716, 1411, 1441, 1712],
 [1011, 1666, 377, 980, 1610, 1686],
 [1229, 1716, 1555, 1564, 1595, 1641, 1355],
 [1056, 1686, 1423, 1399, 935, 1382],
 [935, 1163, 1220, 1186, 1494, 955, 1056],
 [917, 1186, 1163, 1365, 1522, 1056, 1610],
 [955, 1641, 1199, 1600, 1011, 1579, 1666],
 [967, 1663, 1056, 1355, 1666, 1220, 1011],
 [1686, 967, 980, 1602, 1745, 1712, 935],
 [377, 1423, 1153, 1686, 1092, 935, 1382],
 [1666, 1092, 1011, 1449, 1604, 1507],
 [1655, 1399, 1552, 1363, 955],
 [1712, 1438, 1602, 1663, 1600, 1220],
 [1794, 1270, 1348, 1604, 1199, 1563, 1229],
 [1595, 1579, 1436, 853, 1563, 1153, 1555],
 [853, 1629, 917, 1595],
 [1663, 1056, 1092, 967, 955, 1163, 1153],
 [1563, 1363, 1229, 1175, 853, 377, 1186],
 [1610, 1441, 1393, 1436, 1229, 853],
 [1655, 1011, 967, 1153, 1175, 1186, 917],
 [1438, 1649, 1552, 1056, 1163, 1283, 1363],
 [1600, 1229, 1563, 955, 1641, 1011, 1745],
 [1629, 1175, 935, 1602, 1438],
 [1579, 1595, 1175, 1163, 917],
 [1602, 1332, 1449, 377, 1494, 1522],
 [1552, 1242, 1355, 1092, 1441, 1362, 1449],
 [1522, 1555, 1564, 1382, 1602, 1438, 1399],
 [1745, 1199, 1092],
 [1610, 1436, 955, 1220, 853, 1163],
 [1530, 1494, 1365, 1522, 1242, 1283],
 [1712, 1438, 1242, 1348, 1332],
 [1649, 1355, 1332, 1011, 1438, 1393],
 [1494, 1553, 1403, 1363, 1291, 1242],
 [1403, 1411, 1348, 1283, 1270, 1199],
 [1449, 1399, 1242, 1332, 1229],
 [1441, 1384, 1270, 1362, 1332, 1522, 980],
 [1186],
 [1553, 1382, 1291, 1283, 1242],
 [1555, 1522, 1494, 1291, 377, 1332, 1270]]

In [24]:
# get the average of each line in the list
# mean function in the statistics library gives us the averages in the list withour further iterating

from statistics import mean

avg_opponent = [round(mean(i)) for i in opponents_lst]

# check
avg_opponent

[1605,
 1469,
 1564,
 1574,
 1501,
 1519,
 1372,
 1468,
 1523,
 1554,
 1468,
 1506,
 1498,
 1515,
 1484,
 1386,
 1499,
 1480,
 1426,
 1411,
 1470,
 1300,
 1214,
 1357,
 1363,
 1507,
 1222,
 1522,
 1314,
 1144,
 1260,
 1379,
 1277,
 1375,
 1150,
 1388,
 1385,
 1539,
 1430,
 1391,
 1248,
 1150,
 1107,
 1327,
 1152,
 1358,
 1392,
 1356,
 1286,
 1296,
 1356,
 1495,
 1345,
 1206,
 1406,
 1414,
 1363,
 1391,
 1319,
 1330,
 1327,
 1186,
 1350,
 1263]

In [25]:
# there are 64 elements in the list

len(avg_opponent)

64

Finally, we can combine the list we created in a data framen then turn it into a CSV file.

In [26]:
# Putting Name, State, Total Point, Pre-Tournament Rating, and Average Opponents Ratings into DataFrame

df = pd.DataFrame(list(zip(names_final, state_final, total_point_final, ptr_final, avg_opponent)), columns=['Name', 'State', 'Total Points', 'Pre-rating', 'Avg_opponent'])
df

                    Name State  Total Points Pre-rating  Avg_opponent
0               Gary Hua    ON           6.0       1794          1605
1        Dakshesh Daruri    MI           6.0       1553          1469
2           Aditya Bajaj    MI           6.0       1384          1564
3    Patrick H Schilling    MI           5.5       1716          1574
4             Hanshi Zuo    MI           5.5       1655          1501
..                   ...   ...           ...        ...           ...
59            Julia Shen    MI           1.5        967          1330
60         Jezzel Farkas    ON           1.5        955          1327
61         Ashwin Balaji    MI           1.0       1530          1186
62  Thomas Joseph Hosmer    MI           1.0       1175          1350
63                Ben Li    MI           1.0       1163          1263

[64 rows x 5 columns]

In [27]:
# check

df

                    Name State  Total Points Pre-rating  Avg_opponent
0               Gary Hua    ON           6.0       1794          1605
1        Dakshesh Daruri    MI           6.0       1553          1469
2           Aditya Bajaj    MI           6.0       1384          1564
3    Patrick H Schilling    MI           5.5       1716          1574
4             Hanshi Zuo    MI           5.5       1655          1501
..                   ...   ...           ...        ...           ...
59            Julia Shen    MI           1.5        967          1330
60         Jezzel Farkas    ON           1.5        955          1327
61         Ashwin Balaji    MI           1.0       1530          1186
62  Thomas Joseph Hosmer    MI           1.0       1175          1350
63                Ben Li    MI           1.0       1163          1263

[64 rows x 5 columns]

In [28]:
# Saving data into a csv file

df.to_csv('chess_V2.csv' , index=False)